<a href="https://colab.research.google.com/github/ZiYu-Huang/108-2-data-science/blob/master/Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
test=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(test.shape)

(4, 3)


In [ ]:
###基本索引
#陣列索引是由外而內的，以上列ndarray作為範例
#因為都只有一層的索引，所以回傳的都是一排shape為3的ndarray
print(test[0])
print(test[1])
print(test[2])
print(test[3])

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [ ]:
#取出陣列裡的值
print(test[0][2] )
print(test[1][1] )
print(test[2][0] )
print(test[3][2] )

3
5
7
12


In [ ]:
#一次索取多值並改變順序
print(test[0][[1,0,2]] )
print(test[1][[1,0]] )
print(test[2][[2,1]] )
print(test[3][[1,2]] )

[2 1 3]
[5 4]
[9 8]
[11 12]


In [ ]:
print(test[[1,2]][[1,0]]) #先取出test的外層，再由取出中排出順序
print(test[[1,2]][[0,1]])
print(test[[2,1]][[0,1]])
print(test[[1,3]][[1,0]])
print(test[[1,2,3]][[1,0,2]])

[[7 8 9]
 [4 5 6]]
[[4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]]
[[10 11 12]
 [ 4  5  6]]
[[ 7  8  9]
 [ 4  5  6]
 [10 11 12]]


In [ ]:
###切片索引
##使用方式
'''test[起始位置(預設為0):最後位置(預設最終):間隔(預設為1)]''' ##輸出結果不包括最後位置

'test[起始位置(預設為0):最後位置(預設最終):間隔(預設為1)]'

In [ ]:
test[:3] #此範例只有輸入最後位置的參數，起始位置、間隔都是預設值，輸出不包括最後位置

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
test[::-1] #倒敘 只需將間隔數設為-1

array([[10, 11, 12],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 1,  2,  3]])

In [ ]:
test[2,2:0:-1] #索引和切片組合使用  #先取出第二層，再取出第二層中的2和1(有倒敘) #輸出不包括最後位置

array([9, 8])

In [ ]:
test[0:3:2,2]  #索引和切片組合使用 #先取出第0,1,2層，取出間隔為2，再取出其中的2 #輸出不包括最後位置

array([3, 9])