<a href="https://colab.research.google.com/github/ZiYu-Huang/108-2-data-science/blob/master/Day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#布林索引

In [ ]:
import numpy as np
test=np.array([1,2,3,4,11,12,13,14])

In [ ]:
test<10

array([ True,  True,  True,  True, False, False, False, False])

In [ ]:
test[test<10]

array([1, 2, 3, 4])

In [ ]:
test[(test<10) and (test>2)]

ValueError: ignored

In [ ]:
test[(test<10) & (test>2)]

array([3, 4])

#轉置陣列

In [ ]:
test=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
test.shape

(16,)

In [ ]:
test.reshape((4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
test.reshape((2,8))

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [ ]:
test.reshape((4,-1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
test.reshape((-1,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])