<a href="https://colab.research.google.com/github/ZiYu-Huang/108-2-data-science/blob/master/Day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#布林索引
##布林索引很有利於我們之後索取資料使用
###在索引裡放入布林陣列，為True的值會被挑出來


In [1]:
import numpy as np
test=np.array([1,2,3,4,11,12,13,14])

In [2]:
test<10 #我們想要知道陣列裡資料是否小於10，產生布林陣列

array([ True,  True,  True,  True, False, False, False, False])

In [3]:
test[test<10] #放入索引，就獲得了小於10的數值

array([1, 2, 3, 4])

In [4]:
test[(test<10) and (test>2)] #錯誤寫法 #布林索引也能與python的關鍵字and、not、or一起使用 #可是在布林索引時必須打符號 &、!、| 否則會報錯

ValueError: ignored

In [5]:
test[(test<10) & (test>2)] #正確寫法

array([3, 4])

#轉置陣列
#####改變陣列的shape
#####可以使用reshape()這個方法做到，參數是傳入想改變成的shape之tuple

In [6]:
test=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
test.shape

(16,)

In [ ]:
test.reshape((4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
test.reshape((2,8))

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [7]:
test.reshape((4,-1)) #在reshape後面的參數填上-1 它會自動變成符合資料的模樣

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
test.reshape((-1,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])